repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0 # You can specify the version you want
    hooks:
      - id: black
        language_version: python3
        args: [".", "--config", "pyproject.toml"]
