[tool.black]
line-length = 79  # PEP 8 standard line length
target-version = ['py311']  # Specify your Python version
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
# Use single quotes for docstrings (more PEP 8 like)
skip-string-normalization = true 